<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Formulaire Aixplora</title>
    <meta name="description" content="Aixplora vous invite à découvrir le patrimoine culturel d'Aix-en-Provence à travers une carte interactive. Suivez nos parcours pour découvrir les lieux emblématiques de la ville. Plongez dans l'histoire et la culture de la ville avec Aixplora !">
    <link rel="stylesheet" href="../../public/css/style.css">
    <!-- Cette ligne de code correspond à l'ajout d'un lien vers une feuille de style CSS hébergée sur le CDN (Content Delivery Network) de Cloudflare. Cette feuille de style fournit les icônes de la bibliothèque d'icônes Font Awesome, version 5.13.1. -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" />
    <link rel="shortcut icon" type="image/png" href="../../public/img/favicon.png"/>
</head>
    
    <main>
        <?php include '../templates/' . $template . '.phtml'; ?>
    </main>


<script src="../../public/js/formulaire.js"></script>
</body>

</html>