<!DOCTYPE HTML>

<html>

<head>
	<title>AIXPLORA</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css">
	<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">
	<link rel="stylesheet" href="../../public/css/map.css ">
	<link rel="stylesheet" href="../../public/css/cards_modal_map.css ">
	<link rel="stylesheet" href="../../public/css/accordion.css ">
	<link rel="shortcut icon" type="image/png" href="../../public/img/favicon.png"/>

	
</head>


		<section class="bodyMap">

			<!-- div map     -->
			<div id="maCarte"></div>

			<!-- sidebar with icons categories
			<div class="miniSide">
				<a href="http://"><img class="iconeCatSide" src="" alt="" srcset=""></a>
				<a href=""><img class="iconeCatSide" src="" alt="" srcset=""></a>
				<a href="http://"><img class="iconeCatSide" src="" alt="" srcset=""></a>
				<a href=""> <img class="iconeCatSide" src="" alt="" srcset=""></a>
			</div> -->

			<!-- show category -->
			<div class="showCategory">
				<p class="category">Category</p>
			</div>


		
				<?php include '../templates/' . $template . '.phtml'; ?>
		
			

	<!-- Scripts -->
	<script src="../../public/js/jquery.min.js"></script>
	<script src="../../public/js/jquery.scrollex.min.js"></script>
	<script src="../../public/js/jquery.scrolly.min.js"></script>
	<script src="../../public/js/browser.min.js"></script>
	<script src="../../public/js/breakpoints.min.js"></script>
	<script src="../../public/js/util.js"></script>
	<script src="../../public/js/main.js"></script>
	<script src="../../public/js/map.js"></script>



