<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aixplora-Backoffice</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="public/css/adminTable.css ">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">
</head>

<body>


    <!-- RESPONSIF TABLE ADMIN PARCOURS -->

    <!-- <div class="table__wrap"> -->
    <table class="table">
        <thead class="table__header">

            <div class="card shadow my-5">
                <h4 class="card-header">Liste des lieux associés au parcours: <?= $category['titleCategory']; ?></h4>
            </div>


            <!-- start SEARCH FORM -->
            <form action="search_form" method="POST" action="display_searc.php">
                <div class="search">
                    <input type="text" style="color:#ffa142; font-family:'Comfortaa', curive;" class="searchTerm" placeholder="Recherche">
                    <button type="submit" class="searchButton">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                </div>
            </form>
            <!-- end SEARCH FORM -->



            <div style='text-align: center'>
                <button class="btnPlus" style="background-color:#e8a93f">
                    <a href=" <?= buildUrl('admin_addCategory'); ?>">
                        <i class="fa-solid fa-plus"></i>
                    </a>
                </button>
            </div>




            <tr class="table__row">
                <th class="table__cell u-text-left">id</th>
                <th class="table__cell u-text-right">Nom</th>
                <th class="table__cell u-text-right">Lire</th>
                <th></th>
            </tr>
        </thead>

        <tbody>


            <?php foreach ($places as $place) : ?>
                <tr class="table__row">
                    <td class="table__account table__cell">
                        <?= $category['idPlace']; ?>
                    </td>
                    <td class="table__balance table__cell u-text-right u-font-mono"><?= $category['titlePlace']; ?></td>
                    <td class="table__transfer table__cell u-text-center">
                            <!-- eye -->
                            <a href="<?= buildUrl('admin_oneCategory', ['idCategory' => $category['idCategory']]); ?>">
                                <i class="fa-solid fa-eye"> </i>
                    </td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
    <!-- </div> -->




    <script src="../public/main.js"></script>
</body>

</html>