<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="public/css/adminTable.css ">

<!-- RESPONSIF TABLE ADMIN LIEUX -->

<table class="table">
    <thead class="table__header">

    <div class="card shadow my-5">
        <h4 class="card-header">Les Lieux de visite</h4>
    </div>

    <form action="search_form" method="POST" action="display_searc.php">
        <div class="search">
            <input type="text" style="color:#ffa142; font-family:'Comfortaa', curive;" class="searchTerm"
                   placeholder="Recherche">
            <button type="submit" class="searchButton">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>
    </form>

    <!-- ***************************    START  BUTTON PLUS **************************-->
    <div style='text-align: center'>
        <button class="btnPlus" style="background-color:#e8a93f">
            <a href=" <?= buildUrl('admin_addPlace'); ?>" class="infobulle" title="Ajouter un lieu de visite">
                <i class="fa-solid fa-plus"></i>
            </a>
        </button>
    </div>

    <!-- ***************************     END  BUTTON PLUS **************************-->

    

    <!-- **************************************     START TABLEAU  **************************-->
    <tr class="table__row">
        <th class="table__cell u-text-left">id</th>
        <th class="table__cell u-text-right">Nom</th>
        <!-- <th class="table__cell u-text-right">Categories</th> -->
        <th class="table__cell u-text-right">Actions</th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($places as $place) : ?>
        <tr id="place-<?= ($place['idPlace']); ?>" class="table__row">
            <td class="table__account table__cell">
                <?= $place['idPlace']; ?>
            </td>
            <td class="table__balance table__cell u-text-right u-font-mono"><?= ($place['titlePlace']); ?></td>
            <td class="table__limit table__cell u-text-right u-font-mono"><?= $place['dateRegisterPlace']; ?></td>
            <td class="table__available table__cell u-text-right u-font-mono"><?= $place['dateUploadPlace']; ?></td>
            <td class="table__transfer table__cell u-text-center">

                <!-- eye -->
                <a href="<?= buildUrl('allUsers_onePlace', ['idPlace' => $place['idPlace']]); ?>" title="Lire">
                    <i class="fa-solid fa-eye"> </i>
                </a>
                <!-- pen -->
                <a href="<?= buildUrl('admin_editPlace', ['idPlace' => $place['idPlace']]); ?>" title="Modifier">
                    <i class="fa-solid fa-pen"></i>
                </a>
                <!-- trash  -->
                <a class="delete-article-button"
                   href="<?= buildUrl('admin_deletePlaceAjax', ['idPlace' => $place['idPlace']]); ?>"
                   data-ajax="<?= buildUrl('admin_deletePlaceAjax', ['idPlace' => $place['idPlace']]) ?>"
                   title="Supprimer">
                    <i class="fa-solid fa-trash"></i>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<!-- ***************************    START  BUTTON CATEGORIES **************************-->
<div style='text-align: center; margin-bottom: 10px' >
        <button class="btnPlus" style="background-color:#e8a93f">
            <a style="text-decoration:none" href=" <?= buildUrl('admin_categories'); ?>" class="infobulle" title="Allez au dashbord Parcours">
                PARCOURS
            </a>
        </button>
    </div>

    <!-- ***************************     END  BUTTON CATEGORIES  **************************-->
