
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="public/css/adminTable.css ">
    
</head>

<body>
    <style>

        
    </style>

    <!-- RESPONSIF TABLE ADMIN PARCOURS -->
<section style="min-height: 70vh">
    <!-- <div class="table__wrap"> -->
    <table class="table">
        <thead class="table__header">

            <div class="card shadow my-5">
                <h4 class="card-header">Les Parcours</h4>
            </div>


            <!-- start SEARCH FORM -->
            <form action="search_form" method="POST" action="display_searc.php">
                <div class="search">
                    <input type="text" style="color:#ffa142; font-family:'Comfortaa', curive;" class="searchTerm" placeholder="Recherche">
                    <button type="submit" class="searchButton">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                </div>
            </form>
            <!-- end SEARCH FORM -->


            <!-- ***************************      BUTTON PLUS **************************-->
            <div style='text-align: center'>
                <button class="btnPlus" style="background-color:#e8a93f">
                    <a href=" <?= buildUrl('admin_addCategory'); ?>" class="infobulle" title="Ajouter un parcours">
                        <i class="fa-solid fa-plus"></i>
                    </a>
                </button>
            </div>

            <!-- ***************************  END    BUTTON PLUS **************************-->


<!-- **************************************     START TABLEAU  **************************-->
            <tr class="table__row">
                <th class="table__cell u-text-left">id</th>
                <th class="table__cell u-text-right">Nom</th>
                <!-- <th class="table__cell u-text-right">Création</th> -->
                <!-- <th class="table__cell u-text-right">Mise à jour</th> -->
                <th class="table__cell u-text-right">Actions</th>
                <th></th>
            </tr>
        </thead>

        <tbody>


            <?php foreach ($categories as $category) : ?>
                <tr class="table__row">
                    <td class="table__account table__cell">
                        <?= $category['idCategory']; ?>
                    </td>
                    <td class="table__balance table__cell u-text-right u-font-mono"><?= $category['titleCategory']; ?></td>
                    <td class="table__limit table__cell u-text-right u-font-mono"><?= $category['dateRegisterCategory']; ?></td>
                    <td class="table__available table__cell u-text-right u-font-mono"><?= $category['dateUploadCategory']; ?></td>
                    <td class="table__transfer table__cell u-text-center">

                        <!-- map -->
                        <a href="<?= buildUrl('admin_placesByCategory'); ?>" title="Liste des lieux associés">
                            <i class="fa-solid fa-map"></i>
                        </a>
                        <!-- eye -->
                        <a href="<?= buildUrl('admin_oneCategory', ['idCategory' => $category['idCategory']]); ?>" title="Lire">
                            <i class="fa-solid fa-eye"> </i>
                        </a>
                        <!-- pen -->
                        <a href="<?= buildUrl('admin_editCategory', ['idCategory' => $category['idCategory']]); ?>" title="Modifier">
                            <i class="fa-solid fa-pen"></i>
                        </a>
                        <!-- trash  -->
                        <a href="<?= buildUrl('admin_deleteCategoryAjax', ['idCategory' => $category['idCategory']]); ?>" data-ajax="<?= buildURL('admin_deleteCategoryAjax', ['idCategory' => $category['idCategory']]) ?>" title="Supprimer">
                            <i class="fa-solid fa-trash"></i>
                        </a>

                    </td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</section>
<!-- ***************************    START  BUTTON PLACE**************************-->
<div style='text-align: center; margin-bottom: 10px' >
        <button class="btnPlus" style="background-color:#e8a93f">
            <a style="text-decoration:none" href=" <?= buildUrl('admin_places'); ?>" class="infobulle" title="Allez au dashbord Lieux">
                LIEUX
            </a>
        </button>
    </div>

    <!-- ***************************     END  BUTTON PLACE  **************************-->
<!-- **************************************      TABLEAU  **************************-->
    <script src="../public/main.js"></script>
</body>

</html>