<link rel="stylesheet" href="public/css/accordion.css">

<div class="place-grid" style="min-height: 55vh">
    <div>
        <h1><?= $place['titlePlace']; ?></h1>
    </div>

    <div class="displayTable">
        <div class="place-item ">
            <a class="place-title" href="#custom">Notice succincte</a>
            <div class="place-content">
                <div class="place-content-inside">


                    <p class="pAccordion"><?= $place['abstractPlace']; ?></p>
                </div>
            </div>
        </div>

        <div class="place-item ">
            <a class="place-title" href="#custom"> Historique et description </a>
            <div class="place-content">
                <div class="place-content-inside">
                    <p class="pAccordion"><?= $place['descriptionPlace']; ?></p>
                </div>
            </div>
        </div>

        <div class="place-item ">
            <a class="place-title" href="#custom">Coordonnées</a>
            <div class="place-content">
                <div class="place-content-inside">
                    <p class="pAccordion">Adresse: <?= $place['adressPlace']; ?></p>
                    <p class="pAccordion">Latitude: <?= $place['latPlace']; ?></p>
                    <p class="pAccordion">Longitude: <?= $place['longPlace']; ?></p>
                </div>
            </div>
        </div>

        <div class="place-item ">
            <a class="place-title" href="#custom">Images</a>
            <div class="place-content">
                <div class="place-content-inside">

                    <div class="gallery">
                        <figure>
                            <img src="<?php echo 'public/img/imagePlace/' . $place['imagePlace']; ?>" alt="<?= $place['titlePlace']; ?>">
                            <figcaption><?= $place['titlePlace']; ?></figcaption>
                        </figure>
                    </div>

                </div>
            </div>
        </div>

        <div class="place-item ">
            <a class="place-title" href="#custom">En savoir plus</a>
            <div class="place-content">
                <div class="place-content-inside">
                    <p class="pAccordion">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis cursus
                        malesuada. Proin aliquam dignissim nunc, ac hendrerit odio vestibulum nec. In semper id nulla ac
                        vehicula. Suspendisse faucibus, libero sit amet aliquet auctor, orci dui euismod quam, vehicula
                        elementum odio ligula eget turpis. Aliquam commodo condimentum magna at dapibus.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if (Session::hasRole(ROLE_ADMIN)) : ?>
    <!-- ***************************    START  BUTTON PLACE **************************-->
    <div style='text-align: center; margin-bottom: 10px; margin-top: 10px'>
        <button class="btnPlus" style="background-color:#e8a93f">
            <a style="text-decoration:none" href=" <?= buildUrl('admin_places'); ?>" class="infobulle" title="Allez au dashbord Parcours">
                LIEUX
            </a>
        </button>
    </div>

    <!-- ***************************     END  BUTTON PLACE  **************************-->
<?php endif; ?>

<script src="public/js/accordion_map.js"></script>