<!DOCTYPE HTML>

<html>

<head>
	<title>AIXPLORA</title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="public/css/main.css" />
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<noscript>
		<link rel="stylesheet" href="public/css/noscript.css" />
	</noscript>

	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css">
	<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">
	<link rel="stylesheet" href="public/css/map.css ">
	<link rel="shortcut icon" type="image/png" href="public/img/favicon.png" />

	<script src="public/js/map2.js" defer></script>
</head>

<body class="landing is-preload">

	<div id="page-wrapper">

		<header id="header" class="alt">
			<a href="<?= buildUrl('home'); ?>"> <img id="logoTexteAixplora" src="public/img/logos/logoAixplora.png" alt="premier logo du site Aixplora"> </a>
			<div id="iconsContent">
				<?php if (Session::isConnected()) : ?>
					<a href="#" id="geolocation-link"> <img class="iconCategoryNav" src="public/img/iconeCategory/loc_user" alt="Icone pour activer votre géolocalisation" title="Activez votre géolocalisation"></a>
					<a href="#"> <img class="iconCategoryNav" src="public/img/iconeCategory/favourite" alt="Icone pour afficher sur la carte interactive vos lieux de visite favouris" title="Vos lieux de visite favouris"></a>
				<?php endif; ?>
				<?php foreach ($categories as $category) : ?>
					<label><input type='checkbox' id="cat<?= $category['idCategory']; ?>" checked><img class="iconCategoryNav" src="public/img/iconeCategory/<?= $category['iconeCategory']; ?>" alt="Icone pour afficher sur la carte interactive les lieux de visite appartenant au parcours <?= $category['titleCategory']; ?>" title="<?= $category['titleCategory']; ?>"></label>
				<?php endforeach; ?>
			</div>
			

			<!-- **************************
						MENU 
			************************-->
			<nav id="nav">
				<ul>
					<li class="special">
						<a href="#menu" class="menuToggle"><span>Menu</span></a>
						<div id="menu">
							<ul>
								<li><a href="<?= buildUrl('home'); ?>">Home</a></li>

								<?php if (Session::isConnected()) : ?>
									<li><a href="<?= buildUrl('profileUser'); ?>">Votre profil <?= (Session::getUserFirstname()); ?> <?= (Session::getUserLastname()); ?></a></li>
									<li><a href="<?= buildUrl('logout'); ?>">Se deconnecter</a></li>
								<?php else : ?>
									<li><a href="<?= buildUrl('signup'); ?>">Créer un compte</a></li>
									<li><a href="<?= buildUrl('login'); ?>">Se connecter</a></li>
								<?php endif; ?>

								<?php if (Session::hasRole(ROLE_ADMIN)) : ?>
									<li><a href="<?= buildUrl('admin'); ?>">Dashboard Administrateur</a></li>
								<?php endif; ?>
								
								<li><a href="<?= buildUrl('map'); ?>">Carte interactive</a></li>
								<!-- <li><a href="elements.html">Elements</a></li> -->
								<img class='logo' src="public/img/logos/logoCezanne_blue.png" alt="">
							</ul>
						</div>
					</li>
				</ul>
			</nav>
		</header>
		<main>
			<?php include '../templates/' . $template . '.phtml'; ?>
		</main>


		<!-- Footer -->
		<footer id="footer">
			<div class="inner">
				<header>
					<h2>Aixplora</h2>
					<p>A la découverte de notre passé, notre présent et notre futur...</p>
				</header>
				<ul class="actions stacked">
					<li><a href="#" class="button fit primary">Aixplorer</a></li>
				</ul>
			</div>
			<ul class="icons">
				<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
				<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
			</ul>
			<ul class="copyright">
				<li>&copy; Emanuela Rossetti 2022</li>
				<li>Design: <a href="#">E2R</a></li>
			</ul>
		</footer>

	</div>

	<!-- Scripts -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="public/js/jquery.min.js"></script>
	<script src="public/js/jquery.scrollex.min.js"></script>
	<script src="public/js/jquery.scrolly.min.js"></script>
	<script src="public/js/browser.min.js"></script>
	<script src="public/js/breakpoints.min.js"></script>
	<script src="public/js/util.js"></script>
	<script src="public/js/main.js"></script>

	<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
	<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
</body>

</html>