<!DOCTYPE html>
<html lang="fr" >
<head>
  <meta charset="UTF-8">
  <title>Aixplora - Error 403</title>
  <!-- <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'> -->
  <link rel="stylesheet" href="public/css/style404.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="kode-content">
	<div class="container">
		<div class="error-404">
			<h2>Oups!</h2>
			<div class="page-404">
				<p>403</p>
				<span>Accès interdit</span>
			</div>
			<p>Nous sommes désolés, vous ne disposez pas des droits nécessaires pour effectuer cette action.</p>
			<a href="<?=buildUrl('home');?>" class="go-back">Cliquez ici pour retourner chez Aixplora</a>
		</div>   
	</div>   
</div>
<!-- partial -->
  <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script> -->
<!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js'></script> -->
</body>
</html>
