<div class="profile">
    <button class="favourite-button">
        <img id="favouriteIcon" src="public/img/iconeCategory/favourite.png"
             alt="Bouton permettant d'accèder à votre liste de lieux favoris du site Aixplora"
             title="Liste des vos lieux favouris">
    </button>
    <img src="public/img/backgroundForms/imgback08.jpg" alt="Profile Image" class="profile-image">
    <h1 class="profile-name"><?= $profileFirstname; ?> </h1>
    <p class="profile-bio emailUser"> <?= $profileEmail; ?> </p>
    <p class="profile-bio dateRegisterUser"></p>
</div>


